### ISSUE TITLE
IRC Ping timeout stops the bot

### ISSUE THREAD

**Issue by mbasaglia** [mbasaglia/Melanobot_v2#21]
It should reconnect (See also #17)

**Comment by mbasaglia** [comment]
Backtrace from a crash caused by a ping timeout:

```
[2016-04-07 02:26:04]irc>ERROR :Closing Link: EvilAntCyborg by portlane.se.quakenet.org (Ping timeout)
[2016-04-07 02:26:04]irc<QUIT 
[Thread 0x7fffcb7fe700 (LWP 942) exited]
[2016-04-07 02:26:04]irc!Server Error:: Closing Link: EvilAntCyborg by portlane.se.quakenet.org (Ping timeout)
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffcaffd700 (LWP 943)]
0x00007ffff6574067 in __GI_raise (sig=<error reading variable: Unhandled dwarf expression opcode 0x0>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb)
(gdb) bt
#0  0x00007ffff6574067 in __GI_raise (sig=<error reading variable: Unhandled dwarf expression opcode 0x0>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6575448 in __GI_abort () at abort.c:89
#2  0x0000000000000020 in ?? ()
#3  0x0000000000000000 in ?? ()
(gdb) thread 
[Current thread is 33976 (Thread 0x7fffcaffd700 (LWP 943))]
(gdb) info threads
  Id   Target Id         Frame 
* 33976 Thread 0x7fffcaffd700 (LWP 943) "melanobot" 0x00007ffff6574067 in __GI_raise (sig=<error reading variable: Unhandled dwarf expression opcode 0x0>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
  18   Thread 0x7fffca7fc700 (LWP 28076) "melanobot" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  14   Thread 0x7fffcbfff700 (LWP 28072) "melanobot" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  13   Thread 0x7fffe4ff9700 (LWP 28071) "melanobot" 0x00007ffff6627e53 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  12   Thread 0x7fffe57fa700 (LWP 28070) "melanobot" 0x00007ffff6627e53 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  11   Thread 0x7fffe5ffb700 (LWP 28069) "melanobot" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  10   Thread 0x7fffe67fc700 (LWP 28068) "melanobot" 0x00007ffff6627e53 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  9    Thread 0x7fffe6ffd700 (LWP 28067) "melanobot" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  8    Thread 0x7fffe77fe700 (LWP 28066) "melanobot" 0x00007ffff6627e53 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  7    Thread 0x7fffe7fff700 (LWP 28065) "melanobot" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  6    Thread 0x7fffec852700 (LWP 28064) "melanobot" 0x00007ffff6627e53 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  5    Thread 0x7fffed053700 (LWP 28063) "melanobot" pthread_cond_timedwait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  4    Thread 0x7fffed854700 (LWP 28062) "melanobot" 0x00007ffff6627e53 in epoll_wait () at ../sysdeps/unix/syscall-template.S:81
  3    Thread 0x7fffee66a700 (LWP 28061) "melanobot" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7fffeee6b700 (LWP 28060) "melanobot" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  1    Thread 0x7ffff7fdcb00 (LWP 28059) "melanobot" 0x00007ffff6ec0b80 in std::string::reserve(unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6

threads:
1   melanobot::Melanobot::run
2   web::HttpService::run
3   timer::TimerQueue::run
4   ??
5   melanolib::time::basic_timer<std::chrono::_V2::steady_clock>::run
6   ??
7   melanolib::time::basic_timer<std::chrono::_V2::steady_clock>::run
8   ??
9   melanolib::time::basic_timer<std::chrono::_V2::steady_clock>::run
10  ??
11  irc::Buffer::run_output
12  ??
13  ??
14  melanolib::time::basic_timer<std::chrono::_V2::steady_clock>::run
18  melanolib::time::basic_timer<std::chrono::_V2::system_clock>::run
33976 O_o
```

**Comment by mbasaglia** [comment]
Also:

```
2016-04-19 06:56:04]irc>ERROR :Closing Link: EvilAntCyborg by azubu.uk.quakenet.org (Too many connections from your trust (IP) - see https://www.quakenet.org/help/trusts/connection-limit for details.)
[2016-04-19 06:56:04]irc!Server Error:: Closing Link: EvilAntCyborg by azubu.uk.quakenet.org (Too many connections from your trust (IP) - see https://www.quakenet.org/help/trusts/connection-limit for details.)
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
./melanobot.sh: line 88: 27505 Aborted
```
